// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommiTect
{
    internal sealed partial class Vsix
    {
        public const string Id = "CommiTect.a1b2c3d4-e5f6-7890-abcd-ef1234567890";
        public const string Name = "CommiTect – Smart Commit Name Suggestion";
        public const string Description = @"Automatically analyzes your code changes on file save and suggests a clear, professional commit name (Bug Fix, Feature, Refactor, Docs, Tests) using an external backend API.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Mohammed Atef";
        public const string Tags = "git, commit, automation, productivity, source-control";
        public const bool IsPreview = false;
    }
}
